blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/Dr-Nio/aura-path-algorithms/discussions
    about: Please use GitHub Discussions for questions and ideas.
